/*
 * This file was generated by sp65.exe 2.13.9 from
 * oddSize.pcx (3x3, 5 colors, indexed)
 */

#define oddSize_COLORS       5
#define oddSize_WIDTH        3
#define oddSize_HEIGHT       3
const unsigned char oddSize[] = {
    0x03,0x01,0x00,
    0x03,0x11,0x10,
    0x03,0x01,0x00,0x00,
};
