/*
 * This file was generated by sp65.exe 2.13.9 from
 * player.pcx (4x2, 2 colors, indexed)
 */

#define player_COLORS       2
#define player_WIDTH        4
#define player_HEIGHT       2
const unsigned char player[] = {
    0x03,0x40,0x00,
    0x03,0xE0,0x00,
    0x00,
};
